Exception Basic: {
    "class": "Exception",
    "message": "What happened?",
    "code": 0,
    "file": "/Users/yaozm/Documents/develop/laravel-exception-notify/src/Support/helpers.php",
    "line": 90,
    "preview": {
        "  81": "    function exception_notify_report_if($condition, $exception, ...$channels): void",
        "  82": "    {",
        "  83": "        $condition and exception_notify_report($exception, ...$channels);",
        "  84": "    }",
        "  85": "}",
        "  86": "",
        "  87": "if (! function_exists('exception_notify_report')) {",
        "  88": "    function exception_notify_report($exception, ...$channels): void",
        "  89": "    {",
        "âž¤ 90": "        $exception instanceof Throwable or $exception = new Exception($exception);",
        "  91": "",
        "  92": "        ExceptionNotify::onChannel(...$channels)->report($exception);",
        "  93": "    }",
        "  94": "}",
        "  95": "",
        "  96": "if (! function_exists('is_callable_with_at_sign')) {",
        "  97": "    /**",
        "  98": "     * Determine if the given string is in Class@method syntax.",
        "  99": "     *",
        " 100": "     * @param mixed $callback"
    }
}
Exception Trace: [
    "#0 /Users/yaozm/Documents/develop/laravel-exception-notify/tests/FeatureTest.php(36): exception_notify_report('What happened?', 'dump')",
    "#12 {main}"
]
Request Header: {
    "host": "localhost",
    "user-agent": "Symfony",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "accept-language": "en-us,en;q=0.5",
    "accept-charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7"
}
Request Query: []
Request Post: []
Request File: []